title: ArcheoFOSS 2021
description: >
  Edizione XV | 2021 del convegno internazionale ArcheoFOSS: software, hardware, processi, dati e formati aperti nella ricerca archeologica
logo: images/archeofoss-2021.png
url: https://2021.archeofoss.org

exclude:
  - site
  - __*
  - Gemfile
  - Gemfile.lock

sass:
    sass_dir: _sass

collections:
  generale:
    output: true
  archivi:
    output: true
  progetti:
    output: true
  news:
    output: true

defaults:
  -
    scope:
      type: "news" # a collection in your site, in plural form
    values:
      layout: "article"
